name: hello-hub
desc: hello-hub
runbooks:
- name: runbook-3
  desc: runbook-3
  selectors:
  - type: labelSelector
    selector: k8s-app=kube-dns
  doc: demo/runbook-3.md
- name: test
  desc: test
  selectors:
  - type: labelSelector
    selector: kubernetes.io/bootstrapping=rbac-defaults
  - type: jsonPathSelector
    selector: '{.apiVersion}=rbac.authorization.k8s.io/v1'
  - type: jsonPathSelector
    selector: '{.kind}=ClusterRole'
  - type: jsonPathSelector
    selector: '{.metadata.name}=cluster-admin'
  doc: test.md
- name: runbook-4
  desc: runbook-4
  selectors:
  - type: labelSelector
    selector: k8s-app=kube-dns
  - type: labelSelector
    selector: pod-template-hash=7745f9f87f
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=Pod'
  - type: jsonPathSelector
    selector: '{.metadata.name}=coredns-7745f9f87f-98hpf'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=kube-system'
  doc: runbook-4.md
